--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/GabaiII/ArmorDurability
build-by-default: true
branches:
- master
projects: 
  AntiAdvertise:
      path: ""
...
...
© 2020 GitHub, Inc.
